In [40]:
!pip install wget
import pandas as pd
import wget
import numpy as np


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip


Q1. Pandas version

In [3]:
pd.__version__

'2.3.1'

In [10]:
url =  'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'

In [11]:
downloaded_file = wget.download(url)

100% [........................................................................] 874188 / 874188

In [12]:
df = pd.read_csv(downloaded_file)

In [13]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

Q2. Records count

In [17]:
df.shape[0]

9704

Q3. Fuel types

In [18]:
df['fuel_type'].nunique()

2

Q4. Missing values

In [19]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Q5. Max fuel efficiency

In [22]:
df_asia = df[df['origin'] == 'Asia']

In [24]:
max(df_asia['fuel_efficiency_mpg'])

23.759122836520497

Q6. Median value of horsepower

In [30]:
df['horsepower'].median()

np.float64(149.0)

In [31]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [32]:
df_filled = df['horsepower'].fillna(df['horsepower'].mode())

In [33]:
df['horsepower'].median()

np.float64(149.0)

Q7. Sum of weights

In [69]:
df_asia[['vehicle_weight', 'model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [35]:
df_asia[['vehicle_weight', 'model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [94]:
X = df_asia[['vehicle_weight', 'model_year']].head(7).values

In [95]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [96]:
XT = X.T

In [97]:
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [98]:
XTX = X.dot(XT)

In [99]:
XTX

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [100]:
XTXI = np.linalg.inv(XTX)

In [101]:
XTXI

array([[ 2.40662244e+08, -8.18480683e+07, -1.03428022e+08,
        -1.71670448e+08,  2.73403363e+08, -2.15404296e+08,
         5.68558288e+07],
       [ 3.07315072e+08,  8.15201613e+08, -3.50733988e+08,
        -6.67483762e+08,  2.18148252e+07, -6.76280250e+07,
        -5.92596904e+07],
       [-4.86723629e+08, -1.99324915e+08,  1.63505427e+08,
         5.91302899e+08, -1.29792968e+08, -8.84952053e+07,
         1.50819395e+08],
       [-3.32348660e+08, -1.88087428e+08,  3.67957445e+08,
         5.29729004e+08, -1.66174330e+08, -1.66174330e+08,
        -4.26064585e+07],
       [ 1.78956971e+08, -1.78956971e+08, -1.78956971e+08,
        -7.60349662e+07, -1.78956971e+08,  3.57913941e+08,
         7.47586876e+07],
       [-1.78956971e+08, -2.04522252e+08,  6.39132038e+07,
         9.37744128e+06,  1.78956971e+08,  1.78956971e+08,
        -4.77768432e+07],
       [ 2.68435456e+08,  3.83479223e+07,  3.83479223e+07,
        -2.12927011e+08,  0.00000000e+00,  0.00000000e+00,
        -1.3225025

In [102]:
y = ([1100, 1300, 800, 900, 1000, 1100, 1200])

In [103]:
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [104]:
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [105]:
XTXIXT = XT.dot(XTXI)

In [106]:
XTXIXT

array([[ 4.88281250e-04,  5.93006535e-04, -3.79084525e-05,
        -1.33886809e-03,  1.34505555e-04, -1.70670227e-04,
         4.06228092e-04],
       [-1.22070312e-04, -1.22979283e-03, -6.92605972e-05,
         1.87301636e-03,  8.17179680e-05,  3.25858593e-04,
        -3.77714634e-04]])

In [107]:
w = XTXIXT.dot(y)

In [108]:
w

array([ 0.50695184, -0.11579692])

In [109]:
w.sum()

np.float64(0.39115491705218286)