In [2]:
!pip install wget
import pandas as pd
import wget
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9685 sha256=2491d404e562a991ddbbf16a1bcb7f3f1ea9ac27408e50e8888807f93181da66
  Stored in directory: /home/codespace/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip


In [3]:
url =  'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv'

In [4]:
downloaded_file = wget.download(url)

100% [...........................................................] 80876 / 80876

In [5]:
df = pd.read_csv(downloaded_file)

In [6]:
df.head()

lead_source    industry  number_of_courses_viewed  annual_income  \
0      paid_ads         NaN                         1        79450.0   
1  social_media      retail                         1        46992.0   
2        events  healthcare                         5        78796.0   
3      paid_ads      retail                         2        83843.0   
4      referral   education                         3        85012.0   

  employment_status       location  interaction_count  lead_score  converted  
0        unemployed  south_america                  4        0.94          1  
1          employed  south_america                  1        0.80          0  
2        unemployed      australia                  3        0.69          1  
3               NaN      australia                  1        0.87          0  
4     self_employed         europe                  3        0.62          1

In [7]:
df.dtypes

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [9]:
df.isnull().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [10]:
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

In [11]:
for c in categorical_columns:
    df[c] = df[c].fillna('NA')

In [12]:
df.head()

lead_source    industry  number_of_courses_viewed  annual_income  \
0      paid_ads          NA                         1        79450.0   
1  social_media      retail                         1        46992.0   
2        events  healthcare                         5        78796.0   
3      paid_ads      retail                         2        83843.0   
4      referral   education                         3        85012.0   

  employment_status       location  interaction_count  lead_score  converted  
0        unemployed  south_america                  4        0.94          1  
1          employed  south_america                  1        0.80          0  
2        unemployed      australia                  3        0.69          1  
3                NA      australia                  1        0.87          0  
4     self_employed         europe                  3        0.62          1

In [16]:
numerical_columns = list(df.dtypes[(df.dtypes == 'int64') | (df.dtypes == 'float64')].index)

In [17]:
for n in numerical_columns:
    df[n] = df[n].fillna(0.0)

In [18]:
df.head()

lead_source    industry  number_of_courses_viewed  annual_income  \
0      paid_ads          NA                         1        79450.0   
1  social_media      retail                         1        46992.0   
2        events  healthcare                         5        78796.0   
3      paid_ads      retail                         2        83843.0   
4      referral   education                         3        85012.0   

  employment_status       location  interaction_count  lead_score  converted  
0        unemployed  south_america                  4        0.94          1  
1          employed  south_america                  1        0.80          0  
2        unemployed      australia                  3        0.69          1  
3                NA      australia                  1        0.87          0  
4     self_employed         europe                  3        0.62          1

Question 1

In [19]:
df.industry.mode()

0    retail
Name: industry, dtype: object

Retail is the mode of the industry column

In [ ]:
Question 2

In [20]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [21]:
numerical = ['number_of_courses_viewed', 'annual_income',
        'interaction_count', 'lead_score']

In [23]:
df[numerical_columns].corr()

number_of_courses_viewed  annual_income  \
number_of_courses_viewed                  1.000000       0.009770   
annual_income                             0.009770       1.000000   
interaction_count                        -0.023565       0.027036   
lead_score                               -0.004879       0.015610   
converted                                 0.435914       0.053131   

                          interaction_count  lead_score  converted  
number_of_courses_viewed          -0.023565   -0.004879   0.435914  
annual_income                      0.027036    0.015610   0.053131  
interaction_count                  1.000000    0.009888   0.374573  
lead_score                         0.009888    1.000000   0.193673  
converted                          0.374573    0.193673   1.000000

annual_income and interaction_count have the biggest correlation

Question 3

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
df_full_train, df_test = train_test_split(df, test_size = 0.2, random_state = 42)

In [26]:
df_train, df_val = train_test_split(df_full_train, test_size = 0.25, random_state = 42)

In [29]:
df_train.reset_index(drop = True)
df_val.reset_index(drop = True)
df_test.reset_index(drop = True)

lead_source       industry  number_of_courses_viewed  annual_income  \
0      social_media  manufacturing                         2        56070.0   
1                NA          other                         1        78409.0   
2          referral  manufacturing                         2        66206.0   
3            events         retail                         0            0.0   
4    organic_search         retail                         6        62832.0   
..              ...            ...                       ...            ...   
288        referral          other                         2        58981.0   
289  organic_search      education                         1        79448.0   
290              NA      education                         5        66922.0   
291        referral     healthcare                         4        82306.0   
292    social_media         retail                         2        64070.0   

    employment_status       location  interaction_count  lead_score  converted  
0       self_employed    middle_east                  2        0.23          1  
1                  NA      australia                  4        0.79          0  
2            employed      australia                  3        0.30          1  
3       self_employed  north_america                  2        0.98          0  
4          unemployed             NA                  4        1.00          1  
..                ...            ...                ...         ...        ...  
288           student         europe                  3        0.20          1  
289        unemployed  north_america                  4        0.38          0  
290          employed         europe                  5        0.53          1  
291     self_employed    middle_east                  3        0.25          1  
292           student           asia                  2        0.92          1  

[293 rows x 9 columns]

In [30]:
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

In [32]:
del df_train['converted']
del df_val['converted']
del df_test['converted']

In [33]:
from sklearn.metrics import mutual_info_score

In [34]:
def mutual_info_converted_score (series):
    return mutual_info_score(series, y_train)

In [35]:
mi = df_train[categorical_columns].apply(mutual_info_converted_score)
mi.sort_values(ascending = False).to_frame(name= 'mutual information')

mutual information
lead_source                  0.035396
employment_status            0.012938
industry                     0.011575
location                     0.004464

lead_source	has the biggest mutual information score

Question 4

In [41]:
from sklearn.feature_extraction import DictVectorizer

In [42]:
numerical_columns = ['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score']

In [43]:
train_dicts = df_train[categorical_columns + numerical_columns].to_dict(orient = 'records')

In [44]:
train_dicts

[{'lead_source': 'paid_ads',
  'industry': 'retail',
  'employment_status': 'student',
  'location': 'middle_east',
  'number_of_courses_viewed': 0,
  'annual_income': 58472.0,
  'interaction_count': 5,
  'lead_score': 0.03},
 {'lead_source': 'organic_search',
  'industry': 'manufacturing',
  'employment_status': 'student',
  'location': 'middle_east',
  'number_of_courses_viewed': 3,
  'annual_income': 71738.0,
  'interaction_count': 6,
  'lead_score': 0.77},
 {'lead_source': 'paid_ads',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'north_america',
  'number_of_courses_viewed': 3,
  'annual_income': 81973.0,
  'interaction_count': 2,
  'lead_score': 0.59},
 {'lead_source': 'NA',
  'industry': 'technology',
  'employment_status': 'employed',
  'location': 'europe',
  'number_of_courses_viewed': 1,
  'annual_income': 74956.0,
  'interaction_count': 3,
  'lead_score': 0.34},
 {'lead_source': 'organic_search',
  'industry': 'retail',
  'employment_status': 

In [45]:
dv = DictVectorizer(sparse = False)

In [46]:
X_train = dv.fit_transform(train_dicts)

In [47]:
X_train

array([[5.8472e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [7.1738e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [8.1973e+04, 0.0000e+00, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        3.0000e+00],
       ...,
       [8.9042e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [5.0259e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+00]], shape=(876, 31))

In [48]:
from sklearn.linear_model import LogisticRegression

In [49]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [50]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [116]:
val_dicts = df_val[categorical_columns + numerical_columns].to_dict(orient = 'records')
X_val = dv.fit_transform(val_dicts)

In [117]:
y_pred = model.predict(X_val)

In [118]:
y_pred_ = model.predict_proba(X_val)[:,1]

In [123]:
converted_decision

array([[False,  True]])

In [109]:
y_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0])

In [121]:
y_pred_

array([0.61192163, 0.79982617, 0.53021344, 0.47131479, 0.57066132,
       0.44227169, 0.87127669, 0.84883115, 0.83290037, 0.61497801,
       0.54968027, 0.78153088, 0.69039786, 0.77017122, 0.5265944 ,
       0.91706425, 0.53170635, 0.42123049, 0.30146455, 0.84881583,
       0.79488653, 0.73670375, 0.44527211, 0.64838383, 0.4176882 ,
       0.75393418, 0.90166116, 0.33903049, 0.43181431, 0.9680681 ,
       0.92018714, 0.37487988, 0.652301  , 0.90650057, 0.75164117,
       0.64202121, 0.82250075, 0.83375553, 0.659116  , 0.30978853,
       0.78942264, 0.35546366, 0.96517758, 0.63389304, 0.51274195,
       0.53230533, 0.82287785, 0.744074  , 0.73452313, 0.68955217,
       0.46964443, 0.84539252, 0.55635243, 0.92637871, 0.65258021,
       0.61526273, 0.63816995, 0.28304018, 0.48049824, 0.57890618,
       0.35497342, 0.62175051, 0.38960778, 0.61156056, 0.85304278,
       0.75430136, 0.89185954, 0.71946459, 0.95387623, 0.89209517,
       0.75277088, 0.33850139, 0.61376593, 0.51622275, 0.64088

In [73]:
model.coef_

array([[-1.77843867e-05, -1.47154423e-02,  3.39095225e-02,
         2.66248432e-03,  1.15238518e-02, -1.02527697e-01,
        -2.48510995e-02,  4.93604222e-02, -2.01258344e-02,
        -1.34214865e-02, -3.00232200e-03, -9.25991830e-03,
        -3.17957304e-02, -1.60513114e-02,  3.11339155e-01,
         5.12012528e-02,  2.01511698e-02, -1.20346284e-02,
        -1.16021521e-02, -1.15251880e-01,  7.95303436e-02,
        -2.99401329e-02,  3.95843295e-03, -1.14296944e-02,
        -1.12457415e-02, -5.59987025e-03,  8.26402635e-03,
         5.58598769e-03, -3.33967159e-02, -2.52837052e-02,
         4.53752887e-01]])

In [124]:
round((y_val == y_pred).mean(),2)

np.float64(0.7)

In [125]:
from sklearn.metrics import accuracy_score

In [126]:
original_accuracy = accuracy_score(y_val, y_pred)

In [127]:
original_accuracy

0.6996587030716723

0.74 is the accuracy

Question 5}

Question 6

In [128]:
 feature_differences = {}

In [140]:
for feature in X_train:
        # Exclude the current feature
        X_train_reduced = X_train.drop(columns=[feature])
        X_val_reduced = X_val.drop(columns=[feature])

        # Train a new model without the current feature
        model_reduced = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
        model_reduced.fit(X_train_reduced, y_train)
        y_pred_reduced = model_reduced.predict(X_val_reduced)

        # Calculate the accuracy without the current feature
        reduced_accuracy = accuracy_score(y_val, y_pred_reduced)

        # Calculate the difference in accuracy
        accuracy_difference = original_accuracy - reduced_accuracy
        feature_differences[feature] = accuracy_difference

        print(f"Accuracy without '{feature}': {reduced_accuracy:.4f} (difference: {accuracy_difference:.4f})")

    # Find the least useful feature (smallest difference in accuracy)
        least_useful_feature = min(feature_differences, key=feature_differences.get)

        print(f"\nLeast useful feature: {least_useful_feature}")
        

AttributeError: 'numpy.ndarray' object has no attribute 'drop'

In [137]:
X_train.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [138]:
X_train

array([[5.8472e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [7.1738e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [8.1973e+04, 0.0000e+00, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        3.0000e+00],
       ...,
       [8.9042e+04, 0.0000e+00, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        3.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [5.0259e+04, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+00]], shape=(876, 31))

In [139]:
df_train

lead_source       industry  number_of_courses_viewed  annual_income  \
1077        paid_ads         retail                         0        58472.0   
463   organic_search  manufacturing                         3        71738.0   
842         paid_ads     technology                         3        81973.0   
835               NA     technology                         1        74956.0   
837   organic_search         retail                         3        59335.0   
...              ...            ...                       ...            ...   
725   organic_search          other                         1        43907.0   
401     social_media         retail                         3        64969.0   
957               NA      education                         3        89042.0   
992     social_media  manufacturing                         1            0.0   
1267          events        finance                         4        50259.0   

     employment_status       location  interaction_count  lead_score  
1077           student    middle_east                  5        0.03  
463            student    middle_east                  6        0.77  
842           employed  north_america                  2        0.59  
835           employed         europe                  3        0.34  
837            student      australia                  1        0.98  
...                ...            ...                ...         ...  
725           employed      australia                  4        0.33  
401           employed  north_america                  1        0.18  
957           employed           asia                  4        0.75  
992      self_employed         europe                  1        0.65  
1267           student           asia                  3        0.54  

[876 rows x 8 columns]